apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-cosmic-config
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-cosmic-config
subjects:
- kind: ServiceAccount
  name: prometheus-cosmic
  namespace: monitoring
